from reportlab.lib.pagesizes import A4
from reportlab.pdfgen import canvas
from datetime import datetime
import os


def generate_pdf_report(report_text: str, target: str):
    """
    Generate PDF from synthesis report text
    """

    folder = "reports"
    if not os.path.exists(folder):
        os.makedirs(folder)

    filename = f"{folder}/synthesis_{target.replace('=', '').replace('(', '').replace(')', '')}.pdf"

    c = canvas.Canvas(filename, pagesize=A4)
    width, height = A4

    x = 40
    y = height - 40

    for line in report_text.split("\n"):
        if y < 40:
            c.showPage()
            y = height - 40

        c.drawString(x, y, line)
        y -= 14

    c.setFont("Helvetica", 8)
    c.drawString(40, 20, f"Generated by Aarvi Chem AI on {datetime.now()}")

    c.save()
    return filename
