# report_engine.py

def generate_synthesis_report(smiles: str, plan: list) -> str:
    lines = []

    lines.append("AARVI CHEM AI – SYNTHESIS REPORT")
    lines.append("=" * 40)
    lines.append(f"Target Molecule (SMILES): {smiles}")
    lines.append("")

    if not plan:
        lines.append("❌ No feasible retrosynthetic steps found.")
        return "\n".join(lines)

    for idx, step in enumerate(plan, start=1):
        lines.append(f"Step {idx}")
        lines.append("-" * 20)
        lines.append(f"Reaction Type : {step.get('reaction', 'Unknown')}")
        lines.append(f"Reactants     : {step.get('reactants', [])}")
        lines.append(f"Products      : {step.get('products', [])}")
        lines.append(f"Conditions    : {step.get('conditions', 'Heuristic / AI-estimated')}")
        lines.append(f"Notes         : {step.get('notes', '')}")
        lines.append("")

    lines.append("=" * 40)
    lines.append("⚠ DISCLAIMER")
    lines.append(
        "This synthesis route is generated by AI using retrosynthetic heuristics. "
        "It may differ from industrial, patented, or literature-reported routes. "
        "Experimental validation is required."
    )

    return "\n".join(lines)
